[build]
  publish = "dist/"
  command = "npx convex deploy && npx parcel build src/elm-ts/index.html"
  environment = { NODE_VERSION = "18" }
[functions]
  directory = "src/netlify/"
[dev]
  command = "parcel serve src/elm-ts/index.html"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    sentryOrg = "rj-dellecese"
    sentryProject = "scroll"
